username: admin #Имя пользователя для http basic authentication
password: 123456 #Пароль пользователя для http basic authentication
port: 8505 #Порт на котором приложение внутри контейнера будет ожидать входящие подключения (при смене порта, следует учитывать настройки в файле docker-compose.yml)
provider: csp #Используемый криптопровайдер для обращения к сертификату (может принимать значения: csp, openssl)
csp:
  #Блок настроек для криптопровайдера csp
  keystore: HDImage #Хранилище сертификатов (не менять)
  keys:
  - alias: esia #Алиас сертификата (необходим для выполнения запросов к конкретному сертификату. Может быть произвольным)
    name: pfx-dac16c25-dddb-1dc6-5b7e-6d8ef69f9c31 #Имя криптоконтейнера (находится в name.key криптоконтейнера)
    pin:  #Pin код для криптоконтейнера (если он есть, иначе оставить пустым)
openssl:
  #Блок настроек для криптопровайдера openssl
  keysDir: /home/app/openssl_keys #Директория внутри контейнера в которой должны лежать сертификат и ключ в формате pem.
log:
  level: debug
  dir: ./logs
  maxSize: 1048576
  #colors: auto Управление цветным выводом в консоль. Поддерживаемые значения: on, off, auto. По умолчанию: auto
  #maxCount Максимальное количество файлов логов. По умолчанию: 10
  #baseName: signer Базовое имя файла лога. По умолчанию: signer
